### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by travier** [comment]
🎉

**Comment by travier** [comment]
Hum 🤔 

```
Error: D-Bus service file 'org.kde.dolphin.FileManager1.service' has wrong name
error: Failed to install org.kde.dolphin: D-Bus service file 'org.kde.dolphin.FileManager1.service' has wrong name
```

**Comment by travier** [comment]
OK, this one works but I get a dialog with:

```
kf.kio.core: "Could not enter folder tags:/."
```

**Comment by travier** [comment]
I have the same with current stable dolphin flatpak some this might come from somewhere else.

**Comment by tsdgeos** [comment]
I'd say let's get it merged then, it isn't worse than it was

**Pull request merged**
